//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLines
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Forms;

    public partial class Plane
    {
        public String[] str = { "ID", "Model", "Date", "LifeTime", "Ready", "CommanderDetail" };
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plane()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int ID { get; set; }
        public string Model { get; set; }
        public System.DateTime Date { get; set; }
        public int Lifetime { get; set; }
        public bool Ready { get; set; }
        public int Commander { get; set; }
        public string CommanderDetail
        {
            get
            {
                return $"{Commander1.Surname} {Commander1.Name} {Commander1.Patronymic}";
            }
        }
        public string PlaneDetail
        {
            get
            {
                return $"{this.ID}:{this.Model}";
            }
        }
    
        public virtual Commander Commander1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
