//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public String[] str = { "ID", "DepartureAirport", "DestinationAirport","TicketPrice", "Duration" };

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int ID { get; set; }
        public string DepartureAirport { get; set; }
        public string DestinationAirport { get; set; }
        public decimal TicketPrice { get; set; }
        public int Duration { get; set; }
        
        public string RouteDetail
        {
            get
            {
                return $"{this.ID}:{this.DepartureAirport}-{this.DestinationAirport}";
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
