//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public String[] str = { "ID", "PassengerDetail", "FlightDetail" };
        public int ID { get; set; }
        public int PassengerID { get; set; }
        public string PassengerDetail 
        {
            get
            {
                return $"{Passenger.Surname} {Passenger.Name} {Passenger.Patronymic}";
            }
        }
        public int FlightID { get; set; }
        public string FlightDetail 
        {
            get
            {
                return $"{Flight.RouteDetail}";
            }
        }
        public string PasName
        {
            get
            {
                return Passenger.Name;
            }
        }

        public virtual Flight Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
